version: "2"
services:
  db-ts:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${MY_SQL_PASS}
    ports:
     - "9091:3306"